browserstack_runner:
  build_name: "All_Targets" # Name for the browserstack build
  test_script: "./src/browserstack/tests/visit-only.py" # Test script to run
  urls_file: "./urls/manual.yml" # Phishing URLs to test on the devices 
  targets_src: "./src/browserstack/targets/all_targets" # Either the single file or directory of files containing the list of devices/configurations to test on
  randomize_order: True # Randomize the order of the environments to ensure a fair test
  interrupted: False
  continue_point: "0.yml" # If the test was interrupted (specify in above boolean), can continue from a specific file
  unique_id: "" # If test was interrupted, also need to get the 8-character unique ID that was generated so it can just continue
  target_generator:
    targets_directory: "./src/browserstack/targets"
    output_as_file: False # Can either output as a single file (True) or collection of files in directory (False)
    custom_outfile: null # If outputting as single file, can specify custom file name (otherwise null)
    browser_versions_file: "./src/browserstack/targets/browser_versions.yml" # File containing desktop browser versions to limit the test to
    entries_per_file: 6 # My limit with 1 parallel thread is 6 (1 + 5 queued); see https://www.browserstack.com/docs/automate/selenium/queue-tests
  output_analyzer:
    output_directory: "./output_data"

phish_scraper:
  urls_directory: "./urls"
  source_csv: './urls/online-valid.csv'
  num_urls: 10 # Number of URLs to fetch from phishtank (argparse argument has precedence over this value)

cve_searcher:
  cves_directory: "./src/cve_searcher/cves"