# Place any useful snippets of code that we re-use a lot in here

def write_file_source_header(source: str, f=None):
    try:
        f.write("# =======================================\n")
        f.write(f"# FILE GENERATED BY {source}\n")
        f.write("# =======================================\n")
    except Exception as e:
        print(f"Error in write_file_source_header: {e}")